# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.TextField(help_text='Enter a status for others to view', max_length=1000)),
                ('lastSeen', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('bio', models.TextField(help_text='Enter a brief description of yourself', max_length=1000)),
                ('major', models.CharField(max_length=100)),
                ('smokes', models.BooleanField(default=False)),
            ],
        ),
    ]
