# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leaseEnds', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='home',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doma.Home'),
        ),
    ]
